name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: echo thystart

    - name: Install dependencies
      run: make

    - name: Run all
      run: make all

    - name: Run install
      run: make install

    - uses: actions/upload-artifact@master
      with:
        name: exe
        path: ./*.exe
